Styling improvements for [sectionId] pages
OxfordRSE/gutenberg pull request #233
Opened 2024-06-27 09:42 UTC by dankimberley

- Fixed text overflowing prev/next buttons 
- Style improvements for learning outcomes as per #229   
<img width="1330" alt="Section Styling" src="https://github.com/OxfordRSE/gutenberg/assets/10367135/a4b20bac-dd15-4fc5-9df9-e797c9d4a578">

2024-07-02 15:07 UTC, alasdairwilson requested changes

2024-07-02 15:07 UTC, alasdairwilson commented on components/ui/LinkedSection.tsx
> +          className={`group rounded-md border-2 hover:border-4 ${borderColor} ${calcAnchorHeight} w-[150px] text-sm`}
Annoyingly this breaks whatever I had to do to get them to not move when the hover border width changed:

![old](https://github.com/OxfordRSE/gutenberg/assets/60351846/351d61e0-d602-4e31-8832-acccead4eb17)
 versus new:
 
 
![new](https://github.com/OxfordRSE/gutenberg/assets/60351846/b8af9f38-2fda-4f13-bb08-a403de9c0be7)

I have absolutely no idea why? There might be an easy fix but it could certainly be fixed using box shadow rather than border? well I am never certain about anything when it comes to frontend.

BUT, we will spin this into another issue cause I would rather have them move slightly than the current text-overflow that we have.

2024-07-02 15:08 UTC, alasdairwilson commented
Hey, great work 👍 , I have two minor changes regarding the coloring of elements and one thing that we will leave for another issue (the movement due to border size changes.

Other than that, should be good to go.

2024-07-03 11:27 UTC, dankimberley commented
> Hey, great work 👍 , I have two minor changes regarding the coloring of elements and one thing that we will leave for another issue (the movement due to border size changes.
> 
> Other than that, should be good to go.



> Hey, great work 👍 , I have two minor changes regarding the coloring of elements and one thing that we will leave for another issue (the movement due to border size changes.
> 
> Other than that, should be good to go.

Thanks for this! I've committed those changes. Yeah border behaviour definitely not ideal - I'll have a look at the border movement.

2024-07-03 11:55 UTC, alasdairwilson approved these changes
great, thanks @dankimberley

2024-07-03 11:56 UTC, merged