Add edit source button for github.
OxfordRSE/gutenberg pull request #49
Opened 2023-08-22 14:07 UTC by alasdairwilson

This closes #20, linking on each section page to an editable github page of the material.

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/cf8aa779-d240-4c94-a31c-1e4d5841ccfb)

Also adds a link back to /material in the top bar, closes #48 

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/4ff21d5d-be44-42c7-b812-4b95884a5116)

2023-08-23 16:39 UTC, martinjrobins requested changes
Thanks @alasdairwilson, this looks great. Just a couple minor suggesions below

2023-08-23 20:18 UTC, alasdairwilson commented on .env
> +NEXT_PUBLIC_GITHUB_MATERIAL_BASE_URL = "https://github.com/UNIVERSE-HPC/course-material/"
So I will change the env name (and the JS var) to something more generic, but if you don't prepend it with "NEXT_PUBLIC_" you get runtime errors:

```
1 of 1 unhandled error

Unhandled Runtime Error
Error: The provided `href` (/material/[themeId]/[courseId]/undefined/edit/main/software_architecture_and_design/procedural/variables_python.md) value is missing query values (themeId, courseId) to be interpolated properly. Read more: https://nextjs.org/docs/messages/href-interpolation-failed

Call Stack
Router.change
node_modules/next/dist/shared/lib/router/router.js (760:26)
```

This took me absolutely ages to work out a fix for because the error is extremely poorly explained and the way the href in the error message is structured obfuscates it is the baseurl that has broken as it points to theme.id and course.id as the problem when it is the githubbaseurl. What is particularly annoying is the href is correctly rendered in the final html but crashes the page when clicked.

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

Is the reason why but I am not extremely clear on why it has this particularly behaviour. If the env var was never able to be used in an href then I would understand but instead it cant be used on pageload, it must be down to react just urgently trying to do everything impatiently. Although my initial solution of using an if on the basegithuburl var to make the link also does not work because then the dom changes partway through loading (as the variable does appear sometime during the process).

2023-08-24 06:36 UTC, martinjrobins commented on .env
> +NEXT_PUBLIC_GITHUB_MATERIAL_BASE_URL = "https://github.com/UNIVERSE-HPC/course-material/"
ahhh sorry my bad, I didn't realise the NEXT_PUBLIC was required. Best to leave it then

2023-08-29 09:08 UTC, martinjrobins approved these changes
great, thanks @alasdairwilson!

2023-08-29 09:08 UTC, merged